PRAGMA foreign_keys = ON;
CREATE TABLE agencies (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE memberships (agency_id TEXT NOT NULL REFERENCES agencies(id), user_id TEXT NOT NULL REFERENCES users(id), role TEXT NOT NULL CHECK(role IN ('owner','admin','producer','viewer')), PRIMARY KEY(agency_id,user_id));
CREATE TABLE carriers (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), name TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX carriers_agency_idx ON carriers(agency_id);
CREATE TABLE producers (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), name TEXT NOT NULL);
CREATE TABLE commission_schedules (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), carrier_id TEXT NOT NULL REFERENCES carriers(id), rate_basis_points INTEGER NOT NULL, effective_from TEXT NOT NULL, effective_to TEXT);
CREATE TABLE expected_commissions (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), carrier_id TEXT NOT NULL REFERENCES carriers(id), policy_reference TEXT NOT NULL, expected_cents INTEGER NOT NULL, due_date TEXT, currency TEXT NOT NULL DEFAULT 'USD');
CREATE INDEX expected_agency_policy_idx ON expected_commissions(agency_id,policy_reference);
CREATE TABLE statement_imports (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), carrier_id TEXT NOT NULL REFERENCES carriers(id), file_hash TEXT NOT NULL, imported_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(agency_id,carrier_id,file_hash));
CREATE TABLE import_mappings (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), carrier_id TEXT NOT NULL REFERENCES carriers(id), mapping_json TEXT NOT NULL);
CREATE TABLE commission_transactions (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), carrier_id TEXT NOT NULL REFERENCES carriers(id), import_id TEXT REFERENCES statement_imports(id), policy_reference TEXT, amount_cents INTEGER NOT NULL, currency TEXT NOT NULL DEFAULT 'USD', transaction_date TEXT NOT NULL, original_json TEXT);
CREATE INDEX transactions_agency_policy_idx ON commission_transactions(agency_id,policy_reference);
CREATE TABLE reconciliation_runs (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reconciliation_matches (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), run_id TEXT NOT NULL REFERENCES reconciliation_runs(id), expected_id TEXT REFERENCES expected_commissions(id), transaction_id TEXT REFERENCES commission_transactions(id), matched_cents INTEGER NOT NULL);
CREATE TABLE discrepancies (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), run_id TEXT NOT NULL REFERENCES reconciliation_runs(id), expected_id TEXT REFERENCES expected_commissions(id), category TEXT NOT NULL, difference_cents INTEGER NOT NULL);
CREATE TABLE compensation_rules (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), producer_id TEXT NOT NULL REFERENCES producers(id), rate_basis_points INTEGER NOT NULL, effective_from TEXT NOT NULL);
CREATE TABLE producer_payouts (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), producer_id TEXT NOT NULL REFERENCES producers(id), amount_cents INTEGER NOT NULL, status TEXT NOT NULL);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), actor_id TEXT REFERENCES users(id), action TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE subscriptions (id TEXT PRIMARY KEY, agency_id TEXT NOT NULL REFERENCES agencies(id), tier TEXT NOT NULL, status TEXT NOT NULL);
